version: '3'

services:
  app:
    image: node:10-alpine
    build: .
     # context: .
      #dockerfile: Dockerfile.dev
    volumes:
      - ./:/
    ports:
      - 5000:5000
    networks:
      - backend

networks:
  backend:
