version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    environment:
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
      # - "cluster.routing.allocation.disk.watermark.low=100gb"
      # - "cluster.routing.allocation.disk.watermark.high=50gb"
      # - "cluster.routing.allocation.disk.watermark.flood_stage=10gb"
      # - "cluster.info.update.interval=1m"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    #   nofile:
    #     soft: 65536
    #     hard: 65536
  #  volumes:
   #   - ./elasticsearch/data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - backend_backend

  ################ KIBANA ################
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - backend_backend

networks:
  backend_backend:
   # external: true
